"""add note field to appointments

Revision ID: 56b8ebee38b4
Revises: 8a6410e72bdc
Create Date: 2026-07-26 05:09:48.866774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56b8ebee38b4'
down_revision: Union[str, None] = '8a6410e72bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('note', sa.Text(), nullable=True))
    op.create_unique_constraint(None, 'appointments', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='unique')
    op.drop_column('appointments', 'note')
    # ### end Alembic commands ###